# Euler btrfsmaintenance — balance y scrub automáticos
BTRFS_BALANCE_MOUNTPOINTS="/"
BTRFS_BALANCE_PERIOD="monthly"
BTRFS_BALANCE_DUSAGE="75"
BTRFS_BALANCE_MUSAGE="75"

BTRFS_SCRUB_MOUNTPOINTS="/"
BTRFS_SCRUB_PERIOD="weekly"
BTRFS_SCRUB_PRIORITY="idle"
BTRFS_SCRUB_READ_ONLY=false
